### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by harveyvanveltom**
Finalize the testing by adding tests for the IntroActivity, ActivityManager and coin class and subclasses. all classes are now either unit tested, tested by scenarios in the test document or a combination of both.

### CODE REVIEW

**Comment by Mayke93** [comment]
Maybe add some javadoc, otherwise it looks good

**Comment by harveyvanveltom** [comment]
Added the javadoc

**Comment by Faffie** [comment]
Nice tests, thank you!

**Comment by harveyvanveltom** [comment]
Thanks Travis CI. I should have known adding just JavaDoc comments would cause a test to fail in a completely different class that has been there for weeks.

**Comment by harveyvanveltom** [comment]
the tests have been fixed

**Pull request merged**
