### PR TITLE
Set custom socket timeout, handle socket exceptions

### PR DESCRIPTION
**Pull request by Faffie**
Set custom socket timeout.
Handle exceptions (preventing application from crashing).
Do not use streams if socket not available (connection failed).
Use of  android.util.Log for le teammates.

Please review, TEST(!) and merge.

### CODE REVIEW

**Comment by irenevanderblij** [comment]
Really glad you managed to fix the crash when no server is available. However, right now when there is no server available, the app just says connected, en goes to the waiting screen. This is obviously not what we want, right?

**Comment by alanvanrossum** [comment]
Hmm It indeed no longer crashes. However, it's still possible to click the 'start' button and go to the WaitingActivity when no server is found. Can we change this?

**Comment by Faffie** [comment]
I don't recall seeing that happen and all I did was what I described in my original post. Do you want me to look into this as well?

**Comment by irenevanderblij** [comment]
It would be great if you could look at that aswell, yes

**Comment by Faffie** [comment]
Alright then, I really don't want to change your precious code too much but I'll see what I can do.

**Comment by Faffie** [comment]
It was quite easy to update the UI based on the connection (succeed/fail), however, because the connection is being dealt with in a different thread and because we really shouldn't suspend the main thread (using sleep or whatsoever), this requires a different approach.
I'll try to get something more elegant working later. This seems to work, for now.

**Comment by irenevanderblij** [comment]
When there is a server available, the first time you click the connect button, it still says that the connection failed (even though the connection worked). After I click connect for the second time it does work. Any idea why this is the case?

**Comment by Faffie** [comment]
Yes, the UI is updated in a thread different from the networking. We would need to trigger a UI update after the connection is established. I was working on this, until my laptop went sick. :(

**Comment by irenevanderblij** [comment]
If we think this solution is adequate for now, we can merge this. What does the rest think?

**Comment by Faffie** [comment]
I'm willing to implement this the way its supposed to, however that'd require a few rewrites I'm not sure you'd be too comfortable with. Anyway, I do think this fix is better than having the App crash altoghether.

**Comment by irenevanderblij** [comment]
Can the others give their opinions aswell

**Comment by alanvanrossum** [comment]
Seems adequate for now. We're not Google, let's not waste too much time on this if it's gonna be too hard

**Comment by Faffie** [comment]
It won't be too hard, just time consuming and our deadline's near. I wish we were Google. I do agree we have more important things to worry about right now.

**Comment by Faffie** [comment]
Why are we even considering not to merge a fix that prevents the entire application from crashing just because it doesn't update the UI elegantly? Would you rather just have it crash? Why is this even an issue and why does it take four days to make a decision?

**Comment by Mayke93** [comment]
I do think **this is bigger than** "it doesn't update the UI elegantly", because the game does not actually start - even though the player is already registered in the server, and the user may think s/he cannot connect. 
How time consuming would it be to fix this? If it really cannot be fixed, maybe set the text to 'click connect again' at the first try?

**Comment by Faffie** [comment]
That's what I said: it doesn't update the UI elegantly. That's all there is to it. What do you mean by "the game does not actually start"? 
The game will start when the server tells it to. The 'START' button's functionality is redundant as the game will start when the server tells it to, so perhaps remove it alltogether? So what's your alternative? Just let it crash? You demand user experience over stability?
What's a crashing application going to do to your user experience and how is it any better than a textfield/label not updating in time?

**Comment by irenevanderblij** [comment]
I guess I am hesitant to merge this because of the frequencies in which the scenarios will happen. If the IP address in the code is correct (e.g. your dedicated server), then the app player will always be able to connect. This is the scenario that will happen almost all of the time, not the crash. If we merge your pull request, this scenario will always show a mistake in our code. If we would not merge this, the mistake would not even be noticed in almost all cases. 
I get what you are saying about the app being able to crash. I agree that this is very bad. But I also agree with Mayke that this is not a very nice solution. I hope you can also understand my point.
As to merging this or not, I will follow the opinions of the rest of the group. So let me know.

**Comment by Faffie** [comment]
Let the host send a message after the user was registered succesfully, then start a different activity. All problems solved. This basically is what happens right now anyway, just not immediately after registration.

**Comment by Faffie** [comment]
I added another activity launched upon succesful registration. This solves the UI problem. Why you guys would let an application crash, rather than having a networking bug solved with a UI that's not being updated accordingly, is beyond me. The login activity was confusing to me from the start and this couldn't possibly make it worse. Anyway, my other PR should deal with this issue. Merging both should make everyone happy.

**Comment by Faffie** [comment]
The UI is being updated correctly now. I also disabled the back button in the views by overriding the button's functionality.

We were just telling the user that the connection was established succesfully before, even if it wasn't, which... didn't make sense. This is quite a nasty fix but it's way more elegant than having the entire application crash or not informing the user correctly. After my most recent commit I really don't see a reason to postpone this merge any longer.

Can this please be merged?

**Comment by irenevanderblij** [comment]
This seems to work! Nice job!

**Comment by Mayke93** [comment]
This works well, good improvements, I am going to merge this.

**Pull request merged**
