### PR TITLE
Update protocol handling

### PR DESCRIPTION
**Pull request by Faffie**
Updated the networking protocol.

### CODE REVIEW

**Comment by irenevanderblij** [comment]
Minigame C does not show the colorsequence anymore

**Comment by Mayke93** [comment]
You can also do minigame a and b, and then a again. 
Minigame B is also broken, both smartphone players need to complete this, and this is not the case in this refactor. Minigame c does not work anymore.

**Comment by Mayke93** [comment]
Minigame C seems to not receive or parse the colors anymore, so no colors actually show up in the app.

**Comment by Faffie** [comment]
Yeah, uhm, thanks, Mayke, no need to repeat what Irene says.

Irene, that did actually work for me during my tests and it works now.  The sequence was parsed and displayed correctly (perhaps just not sent). 
I guess the object just wasn't registered properly. That should be fixed now in the other components.

Keeping track of the order and game progress is done elsewhere. 
None of your comments in this discussion apply to this update. Nothing here requires fixing.

By the way, could you all please learn how to properly use android.util.Log and call it at strategic places? Debugging without any output is awful.

**Comment by irenevanderblij** [comment]
Everything seems to work now :) 

After minigame B has been merged, all conflicts can be resolved and this can be merged aswell!

**Comment by Faffie** [comment]
I guess this is ready to be pulled now.

**Comment by harveyvanveltom** [comment]
I tested the app and there were no issues on my end. The refactor looks great made the code a lot more cohesive and removed a lot of bad smelling code.

**Comment by Faffie** [comment]
Thanks.

**Pull request merged**
