### PR TITLE
Waitingminigamesquasher

### PR DESCRIPTION
**Pull request by harveyvanveltom**
Waiting activity now has two buttons. one activates the coin game(isn't altered) and the other activates the bug squasher game. if the player has squashed 50 bugs a DONE[WAITING] message is sent to the host.(the same message protocol used by the gyroscope minigame)

### CODE REVIEW

**Comment by alanvanrossum** [comment]
Awesome! this should make the game a lot more fun. I see you can press the back button on your phone to choose the other minigame, that's awesome!
That reminds us we should check all activities for whether this is possible, because sometimes we want this to be possible, but not always.

**Comment by harveyvanveltom** [comment]
fixed merge conflicts.

**Comment by harveyvanveltom** [comment]
I'm glad you like being able to press the back button to choose the other minigame. but I didn't implement that, that is just androids standard functionality. but you're right we don't want that for all minigames so we'll have to look into disabling that button for certain minigames.

**Comment by irenevanderblij** [comment]
This is already disabled in the other games bh overriding the backbutton
funtionality.

As for the rest of this pull request, I will test (and merge)  it when I'm
home.
Op 9 jun. 2016 16:09 schreef "harveyvanveltom" notifications@github.com:

**Comment by irenevanderblij** [comment]
Mostly looks good! In my opinion the bugs are a bit large, but that is not that important for this pull request. I took the liberty to add some javadoc, and also to add the squasher class to the inWaitingActivity method in ConnectionService, so that you advance to a minigame when in the squasher game, instead of getting stuck here. 

There is one thing going wrong now: if you press the back button in the waiting activity games, we get an error. The game does not crash, but I do think we have to take a look at this. I get the following error when I press the back button in the coin game:

06-09 15:35:10.933 4360-4360/com.context.kroket.escapeapp E/ActivityThread: Activity com.context.kroket.escapeapp.minigames.Waiting_Gyroscope has leaked ServiceConnection com.context.kroket.escapeapp.minigames.Waiting_Gyroscope$1@a524686 that was originally bound here
                                                                            android.app.ServiceConnectionLeaked: Activity com.context.kroket.escapeapp.minigames.Waiting_Gyroscope has leaked ServiceConnection com.context.kroket.escapeapp.minigames.Waiting_Gyroscope$1@a524686 that was originally bound here
                                                                                at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1092)
                                                                                at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:986)
                                                                                at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1303)
                                                                                at android.app.ContextImpl.bindService(ContextImpl.java:1286)
                                                                                at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
                                                                                at com.context.kroket.escapeapp.minigames.Waiting_Gyroscope.onStart(Waiting_Gyroscope.java:230)
                                                                                at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                                at android.app.Activity.performStart(Activity.java:6253)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by irenevanderblij** [comment]
I fixed the exception.

Also, I could not find the overridden onBackPressed() method in the other minigames anymore. Don't know where they went, but I added them again.

If someone could review my added changes, I think this can me merged!

**Comment by harveyvanveltom** [comment]
good job on readding the onBackPressed() methods in the other minigames. I just tested locally and i can verify the app works as intended.

**Comment by Faffie** [comment]
Who removed the onBackPressed overrides? _gets pitchfork_

**Comment by Faffie** [comment]
Merging...

**Pull request merged**
