### PR TITLE
Minigamef

### PR DESCRIPTION
**Pull request by irenevanderblij**
Minigame F working!

### CODE REVIEW

**Comment by irenevanderblij** [comment]
I merged development into this branch, but I got _a lot_ of conflicts in both the LockGame class and the ConnectionService class. Mayke and myself both changed a lot in these classes and I really could not make out what to keep and so on. Since Mayke only fixed checkstyle warnings, I discarded her changes in these two classes and placed mine in there. After this we can fix the checkstyle again in these two classes.

**Comment by irenevanderblij** [comment]
I refactored minigame F to be named minigame D, since this is the logical sequence after C. The Waiting minigame (before game D) is fully refactored to waiting.

Please review (and merge)

**Comment by Faffie** [comment]
I see you actually fixed Travis. Are you a psychiatrist?

**Comment by irenevanderblij** [comment]
I am not sure why a psychiatrist would be able to fix travis

**Comment by Mayke93** [comment]
travis is fixed, and you have debugged properly, it works well. I'll fix the checkstyle in eclipse again

**Pull request merged**
