### PR TITLE
Revert "Waitingminigamesquasher"

### PR DESCRIPTION
**Pull request by Faffie**
Reverts alanvanrossum/kroketapp#33

### CODE REVIEW

**Comment by Faffie** [comment]
Appears to be unstable in Emulator. Revert?

**Comment by irenevanderblij** [comment]
Can you elaborate on unstable?

**Comment by Faffie** [comment]
I get exceptions that are fatal (i.e. crash the entire application) and simply exceptions that aren't dealt with. 

```
                                                                          Process: com.context.kroket.escapeapp, PID: 30371
                                                                          java.lang.NoSuchMethodError: android.content.res.Resources.getDrawable
                                                                              at com.context.kroket.escapeapp.minigames.Waiting_Squasher.onCreate(Waiting_Squasher.java:58)
```

**Comment by Faffie** [comment]
You refused to acknowledge something was wrong or didn't even take time to look into this. Harvey said "It's fully tested, I just want you to merge it". I guess I was stupid enough to trust this. Denying my revert request, the arrogance...

**Pull request closed without merging**
