### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by irenevanderblij**
Refactor the app according to the feedback given. No functionality changes.

### CODE REVIEW

**Comment by Mayke93** [comment]
I see you have fixed the fail in the travis build. The new packages are nice and organised. The classnames are nice, because now you can see what they do. You have kept the letters, so we can still see which games come first in the app.

**Comment by Faffie** [comment]
Code's more organised. I'd like to see Javadoc sentences begin with upper case characters, which isn't the case everywhere. The app appears to be less error prone now. Good job.

**Comment by irenevanderblij** [comment]
I changed the Javadoc according to your comment. Think this can me merged now.

**Comment by alanvanrossum** [comment]
Much more clear now, good job.

**Pull request merged**
