### PR TITLE
Waiting minigame

### PR DESCRIPTION
**Pull request by irenevanderblij**
You are now able to play a minigame while waiting for the Oculus player. When you have collected 50 points, a message is sent to the server, which still needs an implementation how to handle this message.

I have not yet added that you keep your score after a minigame triggered by the Oculus player has been started and ended. But I do not think that this is a priority right now.

### CODE REVIEW

**Comment by Mayke93** [comment]
I have tested it and it seems to work well. The transition from the waiting minigame to minigame a triggered minigame works.

**Comment by Faffie** [comment]
Nice minigame. Isn't "mean time" a single word? :camel:

**Comment by irenevanderblij** [comment]
Changed that

**Comment by Faffie** [comment]
I was... joking. Anyway, would you mind changing the variables to lowerCamelCase? :camel:

**Comment by irenevanderblij** [comment]
Not really sure which variables you are talking about. Changed the ones I could find. Also put the Coin classes in a separate package (but did not really know a good name for this)

**Comment by Mayke93** [comment]
travis passes and the names are good.

**Pull request merged**
