### PR TITLE
Launch registered activity upon registration

### PR DESCRIPTION
**Pull request by Faffie**
Launch activity to let user wait after registration was succesful.

### CODE REVIEW

**Comment by irenevanderblij** [comment]
What is the purpose of this pull request?

**Comment by Faffie** [comment]
I wanted to send the user to some 'extra' waiting screen after registration, to deal with the weird experience the user could have when the UI wasn't updated correctly. The host would send a string 'SUCCESS' launching this activity. 

The UI is being updated correctly now, but we may still want this. I don't know.

**Comment by Faffie** [comment]
Is this a feature we (still) want? It's still ready to use.

**Comment by irenevanderblij** [comment]
I'm not sure if we still want this.
On the one hand, it is not really neccesary, since the game always goes to the waiting screen after START is received.
However, you can also click start in the login screen and already go to the waiting screen. In this screen they can already play the waiting minigame. Not sure if we want this? This pull request could resolve that.

**Pull request closed without merging**
