### PR TITLE
F_Lock, latest basis for the new coolest minigame, which features everything a regular turnlock does.

### PR DESCRIPTION
**Pull request by alanvanrossum**
Biggest 'conflict' is the app.iml, but I seem to be unable to gitignore this. Other than the addition of  new files, the only alterations are importing the class in the mainactivity and androidmanifest.xml.
We will have to discuss the way the lock works, if we want it to register a number when you turn left as well as when you turn right, then the methods rotateRight() and rotateLeft() could be simplified in a single rotate(boolean) function.
Also, if anyone has a neater algorithm for the "addToSequence()" method, please do comment and let me know. It should print/save the number that the lock is at at the moment you start turning the other way. Right now it converts the degrees to numbers.

### CODE REVIEW

**Comment by Mayke93** [comment]
nice, it works. You should put some javadoc for the methods!

**Comment by alanvanrossum** [comment]
I've added some javadoc, would you think it's sufficient?

**Comment by irenevanderblij** [comment]
The javadoc looks fine, thanks! However, Travis is failing...

**Comment by irenevanderblij** [comment]
Great job on fixing the travis, I'll merge!

**Comment by alanvanrossum** [comment]
No problem!

**Pull request merged**
