### PR TITLE
Minigames

### PR DESCRIPTION
**Pull request by alanvanrossum**
Added minigame D, the Gyroscopic minigame, in which you need to tilt your phone to collect coins.
Things that still need to be done:
-Score Display
-Sending and processing messages from the server for the correct coin/victory/defeat screen.
-Find a way to not-hardcode the correct playfield-width and length.

### CODE REVIEW

**Comment by harveyvanveltom** [comment]
I fixed the merge conflicts. The minigame looks great If the travis build succeeds it can be merged.

**Comment by irenevanderblij** [comment]
The minigame looks great! Travis however still fails..

**Comment by irenevanderblij** [comment]
Also, there are conflicts again!

**Comment by harveyvanveltom** [comment]
conflicts have  been fixed

**Comment by irenevanderblij** [comment]
Great job! I will merge

**Pull request merged**
