### PR TITLE
Add remoteHost TextField to MainActivity and use value to connect

### PR DESCRIPTION
**Pull request by Faffie**
Added a field to the MainActivity asking the user for the remote host and use the value entered to connect to the remote machine. 

I disagree with hardcoding addresses. I considered using a QR code, some sort of lobby, dynamic DNS or some sort of host discovery, but this still is the best/easiest approach to deal with this problem.

The value entered can simply be a hostname or an IP address.

Please review and share your thoughts.

### CODE REVIEW

**Comment by alanvanrossum** [comment]
Nice I agree with this change for 90%. You could win me over by 100% by changing it so that it used the 'default' ip-address in the code when nothing is entered. This will come in hand when we test something a lot while not changing the ip adress.

**Comment by Faffie** [comment]
Yeah I was considering that in my PR for the VR client as that is what happens for the name anyway, I'll do that for both. Consider it done.

**Comment by Faffie** [comment]
Ok, done.

**Comment by Faffie** [comment]
How did you come up with this 90%? Just curious.

**Comment by alanvanrossum** [comment]
Awesome if the rest agrees I say merge.

**Comment by alanvanrossum** [comment]
(9/10)*100

**Comment by harveyvanveltom** [comment]
I wholeheartedly agree with this change. I think it was ridiculous to ask of people who want to play our game to change the actual code itself every time they use a different IP address. and I like the 'default ip' for development purposes.

**Comment by Faffie** [comment]
Then why didn't you say anything when we discussed this in person? Oh well. I'm glad you both agree this had to be done. I believe 3/5 members think this change was necessary, perhaps 4/5.

Ridiculous! Ridiculous it was, my good sir.

**Comment by irenevanderblij** [comment]
Works very nicely. Can be merged!

**Pull request merged**
