### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by harveyvanveltom**
added and refactored the test suite of the android app.

### CODE REVIEW

**Comment by Faffie** [comment]
_"NO DESCRIPTION PROVIDED"_

THANKS.

Didn't realise getting checkstyle/pmd/findbugs working in gradle would be that simple, nice find. 
Could you make them run in the after_script cycle, so that the build wouldn't fail on those after the build/tests? 
Also, checkstyle writes its result to standard output so its results appear in the buildlog, however pmd and findbugs both write to file. Could you make sure the contents of those files are printed so that they appear in the buildlog?

**Comment by Faffie** [comment]
I pushed a change for travis.yml to print the logs and moved the analysis tools to the after_script cycle.

**Comment by Faffie** [comment]
Damnit, made a few mistakes in the commands/paths (it's late). Retrying...

**Comment by Faffie** [comment]
Alright. Many checkstyle warnings there so far. Perhaps printing the lint output too would be a good idea as well? Alan's minigame is a lint problem.

**Comment by Mayke93** [comment]
I think we can merge this, and then later fix all checkstyle on the development branch. Maybe add some javadoc comments

**Comment by harveyvanveltom** [comment]
added a file generation for checkstyle and added that file to be printed in the build log

**Comment by irenevanderblij** [comment]
There are some conflicts, but I think this can me merged

**Comment by alanvanrossum** [comment]
T̶r̶y̶ ̶t̶o̶ fix your conflicts before merging this.

**Comment by harveyvanveltom** [comment]
the merge conflicts came from the previous pull requests. but now those conflicts have been resolved.

**Comment by alanvanrossum** [comment]
nice job dude

**Comment by Faffie** [comment]
Exactly why are you letting it write its checkstyle warnings to disk to let them be printed eventually while they were printed just fine to begin with?

**Pull request merged**
