### PR TITLE
Added Minigame E: The bug squasher

### PR DESCRIPTION
**Pull request by alanvanrossum**
Let me know what you think

### CODE REVIEW

**Comment by harveyvanveltom** [comment]
I noticed that squashtext isn't centered correctly. and while I like the look of your minigame I don't know what the Oculus player is gonna do while the mobile player is busy squashing bugs. However comments aside the game Itself looks good.

**Comment by alanvanrossum** [comment]
Hmm the squashtext didn't want to center even though I told him to. We will have to think about what the rift user can do during the minigame, indeed. Maybe squash some bugs himself?

**Comment by Mayke93** [comment]
Maybe it would be fun to have a timelimit. Also some pictures of bugs fall of the screen

**Comment by irenevanderblij** [comment]
Travis is failing for your game, try fix this first!

**Comment by Faffie** [comment]
Introducing bugs eh? Anyway, build seems to be failing on lint. Not sure how you managed to get lint to complain, doesn't Android Studio run these checks as well? Perhaps we should discuss this during the next meeting.

**Pull request merged**
